import type { Pattern } from "./types";
// Explicit catalog taxonomy. Isolation/cardio movements without a listed pattern stay unclassified.
const groups: Record<Pattern, string[]> = {
  push: [
    "bench",
    "bench-dip",
    "close-grip-bench-press",
    "dbincline",
    "dbshoulderpress",
    "dip",
    "dumbbell-floor-press",
    "pushup",
    "smithincline",
    "sledpush",
  ],
  pull: [
    "chest-supported-row",
    "dbrow",
    "facepull",
    "latpulldown",
    "pullups",
    "seatedrow",
    "t-bar-row",
    "upright-row",
  ],
  hinge: [
    "cable-pull-through",
    "glute-bridge",
    "hipthrust",
    "kettlebell-swing",
    "rdl",
    "single-leg-romanian-deadlift",
    "sumodeadlift",
  ],
  squat: [
    "bbsquat",
    "box-squat",
    "bulgariansplitsquat",
    "front-squat",
    "gobletsquat",
    "hacksquat",
    "legpress",
    "lunge",
    "reverse-lunge",
    "stepup",
    "wall-sit",
  ],
  carry: ["farmers-carry"],
  core: [
    "bicyclecrunch",
    "cablewoodchop",
    "crunch",
    "deadbug",
    "hanging-knee-raise",
    "hollow-body-hold",
    "legraise",
    "mtclimber",
    "pallof-press",
    "plank",
    "reverse-crunch",
    "russiantwist",
    "sideplank",
    "toe-touch-crunch",
    "v-up",
  ],
};
export const movementPattern = Object.fromEntries(
  Object.entries(groups).flatMap(([pattern, ids]) =>
    ids.map((id) => [id, pattern]),
  ),
) as Record<string, Pattern | undefined>;
